### ISSUE TITLE
Radio Webpages Not Recognised

### ISSUE THREAD

**Issue by Moisie2000** [GetiPlayerAutomator/get-iplayer-automator#596] opened 2016-09-10 10:47 UTC
Hello:

I'm trying to download some older-than-seven-days radio episodes, but the 'Use Current Webpage' and 'Process PID' functions are not recognising the pages as being valid iPlayer pages.

This used to work fine, but I guess site changes at the BBC has broken it.

Here are some examples:

http://www.bbc.co.uk/programmes/b00dn8br
http://www.bbc.co.uk/programmes/b00dn8cf
http://www.bbc.co.uk/programmes/b007jm0m
http://www.bbc.co.uk/programmes/b007jm12
http://www.bbc.co.uk/programmes/b007jm1h
http://www.bbc.co.uk/programmes/b007jm2k

Current using GiA 1.8.6 on OS X 10.11.6.

Many thanks for an otherwise excellent utility.

**Comment by dinkypumpkin** [comment] 2016-09-10 12:40
Report incomplete. If using Safari, duplicate of #569. If using Chrome, cannot reproduce error.

**Closed by dinkypumpkin** 2016-09-10 12:40 UTC
