### ISSUE TITLE
Safari 9.1.1 breaks Get iPlayer Automator Use Current Webpage on ITV hub

### ISSUE THREAD

**Issue by Heart1ight** [GetiPlayerAutomator/get-iplayer-automator#565] opened 2016-05-21 14:48 UTC
After allowing updates to my MBP running Yosemite a couple of days ago, I am no longer able to access ITV programs using the Use Current Webpage option. I get the message "Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page." Current Safari version is 9.1.1. However, when I boot from my backup of 2 days ago that uses Safari 9.0.3, and try the exact same procedure, the Use Current Webpage option works perfectly. This situation is the same whichever program I am trying to access. Has anybody else had this problem, and if so, is there a solution?

**Comment by dinkypumpkin** [comment] 2016-05-22 00:59
If you can't be bothered even to say which GiA version you are using, much search existing tickets,how can you expect a response? Likely duplicate of #564 and #561

**Closed by dinkypumpkin** 2016-05-22 00:59 UTC

**Comment by Heart1ight** [comment] 2016-05-22 09:37
Apologies for not putting GiA version, it is Version 1.8.7-pre.2 (1753), but I did do a search and only found older threads, obviously I am not familiar with the abbreviations and words used on this forum, I am merely a user of GiA and the words I searched did not provide the answer. However, thank you for suggesting #564 & #561, it seems as though Version 1.8.7-pre.3(1756) is the version I'm looking for. Unfortunately there was no link to the download site, but for anybody else also needing this version, it can be downloaded from here: https://sourceforge.net/projects/getiplayerauto/files/prerelease/1.8.7-pre.3/
