### ISSUE TITLE
ITV Series number naming issue

### ISSUE THREAD

**Issue by jefro108** [GetiPlayerAutomator/get-iplayer-automator#582] opened 2016-07-21 20:36 UTC
Get iPlayer Automator only seems to be naming ITV series as series 1.

However when I add a programme by using the current web page option it is showing the series number

![image](https://cloud.githubusercontent.com/assets/12976435/17037854/ca398ae6-4f8a-11e6-93dd-18bfcd00fbcf.png)

Once the programme has been downloaded it is listed only by episode number - it's lost the series information in the processing.

Is there any way the series information could be used in the final programme naming?

**Comment by dinkypumpkin** [comment] 2016-07-21 20:48
Duplicate of #503

**Closed by dinkypumpkin** 2016-07-21 20:48 UTC
Labels: duplicate

**Comment by jefro108** [comment] 2016-07-21 20:55
You say that the information isn't in the meta data https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/503#issuecomment-121730149 but Get iPlayer Automator has the information available - as can be seen in the screenshot - can this not be used? :)

**Comment by dinkypumpkin** [comment] 2016-07-21 21:34
The queue entry just regurgitates the title from the web page header. It isn't parsed to see if it contains a series number. The series number - if it even exists in the web page - isn't always in the title anyway. GiA isn't designed to extract any metadata like series numbers from web pages. By all means feel free to have a go at changing that. It would only be necessary for ITV.

**Comment by jefro108** [comment] 2016-07-21 21:49
Ok thanks for the explanation. I see that the iTV site isn't consistent in what it gives the title of the page but when it doesn't put the Series in the title it appears to put in the Series number into the Description meta tag for all the ones I've looked at.

However more consistent is the page puts the video episode information into the div#video data-video-episode tag.
