### ISSUE TITLE
IPlayer Automator fails to download shows 

### ISSUE THREAD

**Issue by BBCADDICT** [GetiPlayerAutomator/get-iplayer-automator#541] opened 2016-03-06 06:59 UTC
Since yesterday Iplayer automator gets stuck 'connecting' then fails with unknown error code can anyone help?

**Comment by BBCADDICT** [comment] 2016-03-06 15:05
I'm based in the U.S and use BolehVPN which is working fine and allows me to watch shows on both the BBC iplayer and its hub but when I try and download on iplayer Automator it fails

**Comment by dinkypumpkin** [comment] 2016-03-06 15:52
Duplicate of #483

**Closed by dinkypumpkin** 2016-03-06 15:52 UTC
Labels: duplicate

**Comment by larryy** [comment] 2016-03-06 20:51
Undoubtedly related to #483, but I recognize your symptoms and there are some problems specific to BolehVPN right now.  Email me privately if you want to know more.

**Comment by KevanV** [comment] 2016-03-07 06:55
I've checked with my VPN and all working normally.

**Comment by Vangelis66** [comment] 2016-03-07 23:06
@BBCADDICT wrote:

> and use BolehVPN which is working fine

It'd be more prudent **not to name specific VPN** providers here. 
While you say it "is working fine", you may discover regretfully that 
this is no longer the case in future, as the Beeb are out 
on a relentless expedition to blacklist commercial VPN IPs.

> allows me to watch shows on both the BBC iplayer

Do not use this fact as a comparison criterion; 
most TV on demand on the BBC iPlayer is being 
currently streamed via AdobeHDS (and even MPEG-DASH, 
if you have a compatible OS/Web browser and have opted 
in for [iPlayer Beta](http://www.bbc.co.uk/html5)). This delivery method uses plain HTTP, 
while GiA still fetches stuff over RTMP (flashmodes).

And I'm afraid that if the new legislation is rush-passed 
(as early as this summer...) having just a working VPN would 
simply not suffice; UK TV licence credentials would also 
be needed. You can read the (sad) news [here](http://www.theguardian.com/media/2016/mar/02/government-close-bbc-iplayer-loophole-adblocking)

And while it may still be possible to patch GiP 
to accept those login credentials, I fear it'd be 
quite difficult to get valid credentials if in the US 
or elsewhere outside the UK (just as it is impossible 
for me to find working hulu+ credentials despite 
using a US VPN not (yet?) inside hulu's blacklist...).
