### ISSUE TITLE
"Invalid Page" error on "Get current webpage" the Third

### ISSUE THREAD

**Issue by markuswinter** [GetiPlayerAutomator/get-iplayer-automator#553] opened 2016-04-18 05:18 UTC
As I'm not the only one experiencing the issue there is a problem. It might be an incompatibility with installed extensions or something else. The point is that some people have an issue with running the software, and they should be able to exchange their views on the subject in this thread to get to the bottom of the problem.

Furthermore if someone knows the answer they should be able to post the answer which they can't do if you keep closing the thread.

Btw, if you think the police is corrupt then that's your opinion and is not what I said. So please don't misquote me. I said the response is not helpful. If you want to be helpful then great. If you want to be something else then keep closing the issues. But think for a moment: what would you say if Apple, Microsoft, or whoever would react like that on their boards?

**Comment by dinkypumpkin** [comment] 2016-04-18 09:59
If "Apple, Microsoft, or whoever" tell me that my bug report can't be reproduced (and this has happened to me plenty of times), I try to find a better test or more information to make my case. If I can't, I take my lumps and move on. I don't moan about them closing my ticket, and I don't accuse them of not being helpful when they went to the trouble to test the case I presented. A closed ticket doesn't prevent somebody from commenting on your complaints if they wish to do so. Nor does it prevent somebody from posting a solution if they find one. But I hope nobody wastes your time by replying with something as useless as "It might be an incompatibility with installed extensions or something else". If you can't be bothered to investigate your own machine, I or anyone else would have no way of knowing what is going on. But if you do in fact have something on your machine that mangles ITV web pages and prevents GiA from parsing the information from them, there is likely nothing that can be done about it short of removing the "installed extensions or something else". Either the necessary information is there, or it isn't.

Duplicate of #552

**Closed by dinkypumpkin** 2016-04-18 09:59 UTC
Labels: duplicate

**Comment by mostlyotter** [comment] 2016-04-18 10:46
I'll exchange my views on the issue.

I tried your Sweeney link on 10.10.11 using 1.8.7-pre.2 (and a vpn) with no problem. I doubt that helps you much.

Equating one of the world's most highly-valued companies (Apple's current market cap exceeds $US 600 billion) with an individual developer who won't even accept donations seems pointless.

Moreover, as a Mac user since 1998, I know exactly how limited Apple's support is. Customers who want to communicate with Apple support after 90 days from the purchase date must pay for AppleCare. Customers can talk to an Apple developer in their dreams.

Customers who find a bug must submit feedback, receive no answer and wait with everyone else for Apple to decide to react. If you do read the Apple Support forums, you'll know that decision can take a long, long time. You'll also know that threads are promptly locked if the question is about a beta version of OS X. Please note that GiA 1.8.7-pre.2 is a beta version.

My only frustration with dinkypumpkin is that there's no way to thank him without wasting his time. I wish thanks were allowed once a year, perhaps on Halloween.

As this shows that others can respond, please don't open a fourth issue.
