### ISSUE TITLE
Can't find normal versions of The Musketeers

### ISSUE THREAD

**Issue by matthew-w** [GetiPlayerAutomator/get-iplayer-automator#460] opened 2015-01-25 21:52 UTC
When I try to download The Musketeers series 2 episode 3, I get a download failure:-

BBC Download (ID=1585): Downloading The Musketeers: Series 2 - 3. The Good Traitor
INFO: Using Proxy http://82.146.147.112:80
1585:	The Musketeers: Series 2 - 3. The Good Traitor, BBC One, Action & Adventure,Drama, default
INFO: 1 Matching Programmes
INFO: No versions of this programme were selected (available versions: audiodescribed)
BBC Download (ID=1585): The Musketeers: Series 2 - 3. The Good Traitor Failed

This happens whether I go via the PVR, a manual search or 'use current webpage'. I have also tried using a VPN instead of the proxy with no difference

If I go to the player website I can watch a normal version in HD that is not audio described. This has not happened on any previous versions and I am not doing anything different. 

Thanks

Matt

**Comment by dinkypumpkin** [comment] 2015-01-26 00:10
Duplicate of #456

**Closed by dinkypumpkin** 2015-01-26 00:10 UTC
Labels: duplicate
