### ISSUE TITLE
ITV Feed and Marcella

### ISSUE THREAD

**Issue by rogercuthbert** [GetiPlayerAutomator/get-iplayer-automator#560] opened 2016-05-18 06:12 UTC
I have been unable to get The ITV Marcella episodes to show up in the search or PVR and also fail when trying to download using the webpage pid.

I have seen other posts mentioning the ITV index not working is this still the case or is there any fix?

**Comment by dinkypumpkin** [comment] 2016-05-18 06:18
Duplicate of #547

**Closed by dinkypumpkin** 2016-05-18 06:18 UTC
Labels: duplicate

**Comment by rogercuthbert** [comment] 2016-05-18 06:23
Ok sorry didn't see that one.  Thanks. Will try the pre release version. Apologies.

**Comment by di-fish** [comment] 2016-05-18 08:56
Same problem as rogercuthbert and I am using the pre-release version.  Worked fine until today.  ITV must have done something to scupper this app.

**Comment by ndcoxhead** [comment] 2016-05-18 09:00
I have downloaded Marcella 8 and others successfully today with 1.8.7-pre.2 (1753).

**Comment by ndcoxhead** [comment] 2016-05-18 09:07
OS 10.11.4, using Safari v 9.1 (11601.5.17.1) to get the PID.

**Comment by rogercuthbert** [comment] 2016-05-18 09:39
I can confirm Use Webpage has worked for me on Marcella and the Pre Release 1.8.7 GIA.  I an using OSX 10.11.4 on an iMac 5k.  Safari version Version 9.1 (11601.5.17.1)

**Comment by di-fish** [comment] 2016-05-18 09:39
Looks like 10.11.5 is the problem! Suggest do not upgrade, but how long before Geitiplayer Automator is upgraded is a question - I can not upgrade because of one app. pity another good app probably for the bin.

**Comment by dinkypumpkin** [comment] 2016-05-18 10:55
10.11.5 is not the problem. The latest pre-release build works fine on 10.11.5. Don't post misinformation based on a single data point. I'm locking this thread to prevent any more hijacking. If you have a problem, create a new ticket and report it properly.
