### ISSUE TITLE
Absolutely no ITV cache updating since 04 Apr

### ISSUE THREAD

**Issue by UbiGit** [GetiPlayerAutomator/get-iplayer-automator#568] opened 2016-05-27 15:38 UTC
Since "Mon 04 Apr 2016" Get-iPlayer has not shown any new TV scheduled programmes for ITV in a Search or latest itv.cache update (forced or otherwise). 

BBC tv.cache continues to update programme schedules correctly and fully every day, inc. current date 27/05/2016.

This despite clean installs of OS X 10.11.5 and Get-iPlayer 1.8.7-pre.3. My Get-iPlayer Prefs have remained unchanged for years with never a hitch until the above date. I am a UK based financial donor of Get-iPlayer because I've loved its capabilities and made extensive use of them.

I've been following/reading/ ITV "Issues" posted here, but on two occasions when I interjected merely to say "me too", I was brusquely kicked for "Hijacking".

Anyhow, please would someone let me know which Get-iPlayer logs/files/screenshots I am required to upload to get assistance with this?

**Comment by dinkypumpkin** [comment] 2016-05-27 15:41
Duplicate of #547

**Closed by dinkypumpkin** 2016-05-27 15:41 UTC
Labels: duplicate
