### ISSUE TITLE
Not detecting open ITVHub page

### ISSUE THREAD

**Issue by BemusedOne** [GetiPlayerAutomator/get-iplayer-automator#627] opened 2017-04-21 19:09 UTC
I have an ITV hub page open (it's the only window), but when I click use current webpage, GIA says I don't have a valid page open. It works fine with the BBC.

**Comment by Moisie2000** [comment] 2017-04-21 20:41
Same here. Usually works - but not this evening.
GiA 1.8.7.

**Comment by dinkypumpkin** [comment] 2017-04-21 21:58
ITV URLs have changed. This will require a new build to fix. There is no workaround.

**Comment by Mac-Man-APH** [comment] 2017-04-22 07:06
At least you know what the problem is so where will the new build be located as old link to beta version has disappeared?

**Comment by erikmh** [comment] 2017-04-22 23:34
Looks like ITV is now forcing https instead of http.

**Comment by petertribe** [comment] 2017-04-22 23:50
I've done a pull request which should fix this bug...

https://github.com/GetiPlayerAutomator/get-iplayer-automator/pull/629

**Comment by robincm** [comment] 2017-04-23 05:59
Where will we get this updated version please? - the "pre-" (beta) version site seems to have disappeared.

**Comment by bevanting** [comment] 2017-04-23 23:43
Hi, newbie here. I'm also interested in finding this updated version. Thank you.

**Comment by naq59** [comment] 2017-04-24 07:30
I´d also really appreciate a fix for this ITV change. Many thanks in advance

**Comment by tjdj1** [comment] 2017-04-24 10:00
this older version works 1.8.4 here is a link     https://github.com/GetiPlayerAutomator/get-iplayer-automator/releases

**Comment by naq59** [comment] 2017-04-24 10:28
Unfortunately I can´t get 1.8.4 to work with ITV here

**Comment by dinkypumpkin** [comment] 2017-04-24 10:42
You shouldn't need to go back further than 1.8.6 to get the old ITV functionality.

**Comment by erikmh** [comment] 2017-04-24 11:07
> "Use Current Webpage" still won't work for ITV, but you probably won't need it.

Umm. How else can you queue anything up for download? "Use Current Webpage" is vital functionality.

**Comment by dinkypumpkin** [comment] 2017-04-24 11:16
Not if you have rolled back to 1.8.6 and thus restored the old ITV functionality, which once again gives you a searchable cache of ITV programmes. That assumes you leave Quick Caching deselected in Preferences, which is the only way GiA works at the moment.

**Comment by naq59** [comment] 2017-04-24 11:48
That´s correct, using the search function it works again. Thanks for the tip. Will there be a new version at some point to re-enable the Current Website function?

**Comment by erikmh** [comment] 2017-04-24 12:18
Yes, @dinkypumpkin, thanks for the instructions. I can’t say I’m a fan (several extra steps, and it’s much harder to figure out whether an episode is the one I want) — but it’s obviously *much* better than no work-around at all. I look forward to a release with @petertribe’s update.

**Comment by tjdj1** [comment] 2017-04-24 17:44
Sorry forgot to say just use normal search for itv and it works not webpage

**Comment by hugofalkman** [comment] 2017-04-25 21:15
Thanks madkub and dinkypumpkin. After merge of pull request #630  I cloned source and built release in Xcode. Works fine. 😉

**Closed** 2017-04-25 22:57 UTC
Labels: bug

**Comment by dinkypumpkin** [comment] 2017-04-25 23:01
Closed by #631
