### ISSUE TITLE
"Invalid Page" error on "Get current webpage" again

### ISSUE THREAD

**Issue by markuswinter** [GetiPlayerAutomator/get-iplayer-automator#552] opened 2016-04-17 22:09 UTC
First off, please don't close issues so quickly just because they don't happen on your system. Somebody else has reported the same issue in another thread, got the same canned reply, now what? That is not the way to find where the problem is. That's like going to the police to report a burglary and them saying "Well, nobody broke in here. Case closed.". Not exactly helpful.

I stated exactly which version I'm using so the reply "make sure you use this version" was a bit puzzling.

It used both Safari and Firefox and saw the problem with both. That Firefox isn't supported is good to know but doesn't invalidate the issue.

**Comment by dinkypumpkin** [comment] 2016-04-17 23:02
Since I'm the one who is going to fix any bugs, it makes all the difference in the world that I can't duplicate the error. I can't fix bugs that I can't see. If you can find the bug, by all means post the details.  Until then, there is nothing I can do for you. 

What puzzles me is why reminding you to make sure of the version in use should be puzzling to you. You wouldn't be the first person to have multiple versions of GiA installed and launch the wrong one. But in your puzzlement you decided to equate me with corrupt, incompetent police. I don't think we're going to make any progress on that basis.

Duplicate of #551

**Closed by dinkypumpkin** 2016-04-17 23:02 UTC
Labels: duplicate
