### ISSUE TITLE
Get current webpage fails when url is appended with #play

### ISSUE THREAD

**Issue by joewestcott** [GetiPlayerAutomator/get-iplayer-automator#504] opened 2015-07-22 17:37 UTC
Sometimes, depending on how you landed on the page the url will be appended by #play, causing GiA to fail parsing the link.
This happens when a user clicks the play button icon inside the programme thumbnail instead of the image or text, such as on this page: http://www.bbc.co.uk/radio1/programmes/schedules

Solution, ignore everything in the url after the hashtag.

**Comment by dinkypumpkin** [comment] 2015-07-22 17:38
Duplicate of #502

**Closed by dinkypumpkin** 2015-07-22 17:38 UTC
Labels: duplicate
