### ISSUE TITLE
BBC videos won't download 

### ISSUE THREAD

**Issue by evelynrb** [GetiPlayerAutomator/get-iplayer-automator#520] opened 2015-10-26 06:48 UTC
Below is the download log - no BBC contents are able to be downloaded any more.  ITV content works fine but for months now BBC just won't download.   Please help.  EvelynB

Downloading Show 1/1:

BBC Download (ID=1101): Downloading The Graham Norton Show: Series 18 - Episode 5
INFO: Using Proxy http://178.79.147.113:3128
1101:	The Graham Norton Show: Series 18 - Episode 5, BBC One, , default
INFO: 1 Matching Programmes
INFO: Checking existence of default version
INFO: flashhd2,flashhd1,flashhigh2,flashhigh1,flashvhigh2,flashvhigh1 modes will be tried for version default
INFO: Trying flashhd2 mode to record tv: The Graham Norton Show: Series 18 - 5. Episode 5
INFO: File name prefix = The Graham Norton Show Series 18 - 5. Episode 5 ((flashhd))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/evelynbrechtlein/Documents/The Graham Norton Show Series 18/The Graham Norton Show Series 18 - 5. Episode 5 ((flashhd)).partial.mp4.flv via RTMP
INFO: skipping flashhd2 mode
INFO: Trying flashhd1 mode to record tv: The Graham Norton Show: Series 18 - 5. Episode 5
INFO: File name prefix = The Graham Norton Show Series 18 - 5. Episode 5 ((flashhd))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/evelynbrechtlein/Documents/The Graham Norton Show Series 18/The Graham Norton Show Series 18 - 5. Episode 5 ((flashhd)).partial.mp4.flv via RTMP
INFO: skipping flashhd1 mode
INFO: Trying flashhigh2 mode to record tv: The Graham Norton Show: Series 18 - 5. Episode 5
INFO: File name prefix = The Graham Norton Show Series 18 - 5. Episode 5 ((flashhigh))                 
INFO: Connected...
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/evelynbrechtlein/Documents/The Graham Norton Show Series 18/The Graham Norton Show Series 18 - 5. Episode 5 ((flashhigh)).partial.mp4.flv via RTMP
INFO: skipping flashhigh2 mode
INFO: Trying flashhigh1 mode to record tv: The Graham Norton Show: Series 18 - 5. Episode 5
INFO: File name prefix = The Graham Norton Show Series 18 - 5. Episode 5 ((flashhigh))                 
INFO: Connected...
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/evelynbrechtlein/Documents/The Graham Norton Show Series 18/The Graham Norton Show Series 18 - 5. Episode 5 ((flashhigh)).partial.mp4.flv via RTMP
INFO: skipping flashhigh1 mode
INFO: Trying flashvhigh2 mode to record tv: The Graham Norton Show: Series 18 - 5. Episode 5
INFO: File name prefix = The Graham Norton Show Series 18 - 5. Episode 5 ((flashvhigh))                 
INFO: Connected...
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/evelynbrechtlein/Documents/The Graham Norton Show Series 18/The Graham Norton Show Series 18 - 5. Episode 5 ((flashvhigh)).partial.mp4.flv via RTMP
INFO: skipping flashvhigh2 mode
INFO: Trying flashvhigh1 mode to record tv: The Graham Norton Show: Series 18 - 5. Episode 5
INFO: File name prefix = The Graham Norton Show Series 18 - 5. Episode 5 ((flashvhigh))                 
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/evelynbrechtlein/Documents/The Graham Norton Show Series 18/The Graham Norton Show Series 18 - 5. Episode 5 ((flashvhigh)).partial.mp4.flv via RTMP
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
INFO: skipping flashvhigh1 mode
ERROR: Failed to record 'The Graham Norton Show: Series 18 - 5. Episode 5 (b06kqbwt)'
BBC Download (ID=1101): The Graham Norton Show: Series 18 - Episode 5 Failed

AppController: Downloads Finished

**Comment by dinkypumpkin** [comment] 2015-10-26 10:25
Duplicate of #483

**Closed by dinkypumpkin** 2015-10-26 10:25 UTC
