### ISSUE TITLE
Proxies Not Working

### ISSUE THREAD

**Issue by the-saint** [GetiPlayerAutomator/get-iplayer-automator#492] opened 2015-06-14 20:15 UTC
Provided proxies have not been working for me for about a week. I can get a public proxy to work but only after trying many of them and they don''t work for very long. Sometimes no proxies work at all. I'm not sure what's going on.

**Comment by dinkypumpkin** [comment] 2015-06-14 20:23
Duplicate of #483

**Closed by dinkypumpkin** 2015-06-14 20:23 UTC
