### ISSUE TITLE
Problems downloading House of Fools Series 2 Episode 1

### ISSUE THREAD

**Issue by upekshapriya** [GetiPlayerAutomator/get-iplayer-automator#473] opened 2015-02-18 14:08 UTC
When I try to download House of Fools Series 2 Episode 1 the result is an unresumable fragment of the file. See log at  https://gist.github.com/upekshapriya/33dfe7a8202b7d5b65c7

**Comment by dinkypumpkin** [comment] 2015-02-18 14:44
Insufficient info.  See Verbose Log page in wiki and try again.

**Comment by upekshapriya** [comment] 2015-02-18 15:18
Sorry I turned on verbose while the program was started. I guess it didn't register. Updated the log gist now :)

**Comment by dinkypumpkin** [comment] 2015-02-18 15:43
Duplicate of #467.  Servers are misbehaving.  It works here, but others have had the same problem.  All you can do is delete the partial download and try again.  The alternative is to temporarily switch Flash - HD to Flash - Very High in preferences to download a lower-quality video and avoid the misbehaving server.

**Closed by dinkypumpkin** 2015-02-18 15:43 UTC
Labels: duplicate

**Comment by upekshapriya** [comment] 2015-02-18 15:50
Tried it again and it works now. Thanks for your response.
