### ISSUE TITLE
BBC TV Programs not visible.

### ISSUE THREAD

**Issue by mattandbarnie** [GetiPlayerAutomator/get-iplayer-automator#488] opened 2015-06-09 07:41 UTC
Has there been a change in the indexing for BBC programs in the last week? I could find them last monday but when I rechecked on Sunday 7th June 2015 non were visible.

Running Version 1.8.5 (1735) on a Yosemite Mac

Cheers, 

Matt

**Comment by mattandbarnie** [comment] 2015-06-09 07:42
Forgot to mention - UK based, connecting via Talktalk and Virgin Media

**Comment by mattandbarnie** [comment] 2015-06-09 07:44
Forgot to mention - UK based, using TalkTalk and Virgin Media.

BBC radio works fine as does the ITV feed.

**Comment by dinkypumpkin** [comment] 2015-06-09 08:14
Duplicate of #487

**Closed** 2015-06-09 08:17 UTC
Labels: duplicate
