### ISSUE TITLE
Downloading ITV

### ISSUE THREAD

**Issue by wdavies39** [GetiPlayerAutomator/get-iplayer-automator#544] opened 2016-03-25 15:20 UTC
I'm having problems using GIA v. 1.8.6. (1741) when downloading from the ITV Player - it appears as the "ITV Hub" on my MBP, and GIA cannot search any shows on it, or even cannot download from a running show if I use the "Use Current Webpage" button.  The BBC iPlayer works fine.

Can anybody offer any help. There's not much worth watching on ITV, but they do carry the BTCC which is compulsory viewing.

Thanks

Walt

**Comment by dinkypumpkin** [comment] 2016-03-25 15:24
duplicate of #525

**Closed by dinkypumpkin** 2016-03-25 15:24 UTC
