### ISSUE TITLE
Nothing from BBC iPlayer downloads

### ISSUE THREAD

**Issue by Grimfool** [GetiPlayerAutomator/get-iplayer-automator#537] opened 2016-02-13 13:20 UTC
I use a VPN here in the US and until this morning I was able to download both BBC & ITV. I can only download ITV now. The BBC website  say that If a VPN is being used it must be able to determine that it is coming from the UK

**Comment by dinkypumpkin** [comment] 2016-02-13 13:30
Duplicate of #483

**Closed by dinkypumpkin** 2016-02-13 13:30 UTC
