### ISSUE TITLE
BBC HD Feeds No Longer Working

### ISSUE THREAD

**Issue by Radar68** [GetiPlayerAutomator/get-iplayer-automator#469] opened 2015-02-10 13:47 UTC
Trying to download any BBC HD feed doesn't work.  Falls back to Very High in most cases as this is the 2nd choice.  I know HD feed is available.  Example from log is as follows.  

***************************************
AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=434): Downloading EastEnders - 09/02/2015
434:	EastEnders - 09/02/2015, BBC One, Drama,Soaps, default
INFO: 1 Matching Programmes
INFO: Checking existence of default version
INFO: flashhd2,flashhd1,flashvhigh2,flashvhigh1,flashhigh2,flashhigh1 modes will be tried for version default
INFO: Trying flashhd2 mode to record tv: EastEnders - 5011. 09/02/2015
INFO: File name prefix = EastEnders - 5011. 2015-02-09 ((flashhd))                 
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/administrator/Movies/TV Shows/EastEnders/EastEnders - 5011. 2015-02-09 ((flashhd)).partial.mp4.flv via RTMP
INFO: skipping flashhd2 mode
INFO: Trying flashhd1 mode to record tv: EastEnders - 5011. 09/02/2015
INFO: File name prefix = EastEnders - 5011. 2015-02-09 ((flashhd))                 
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/administrator/Movies/TV Shows/EastEnders/EastEnders - 5011. 2015-02-09 ((flashhd)).partial.mp4.flv via RTMP
INFO: skipping flashhd1 mode
INFO: Trying flashvhigh2 mode to record tv: EastEnders - 5011. 09/02/2015
INFO: File name prefix = EastEnders - 5011. 2015-02-09 ((flashvhigh))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
***************************************

Has only just started in the last 24 hours.

I'm using the following setup.
System OSX 10.10.2
GiA 1.8.4

**Comment by dinkypumpkin** [comment] 2015-02-10 14:57
I will assume you are not in the UK, in which case this is a duplicate of #467.  If you are in the UK, see Verbose Log page in wiki and post a full log.

**Closed by dinkypumpkin** 2015-02-10 14:57 UTC
Labels: duplicate, non-uk
