### ISSUE TITLE
BBC Downloads fail  #2

### ISSUE THREAD

**Issue by tonyaus** [GetiPlayerAutomator/get-iplayer-automator#466] opened 2015-02-02 23:11 UTC
Hi dinkypumpkin

Thanks for the quick reply.  Here is the gist ref: https://gist.github.com/tonyaus/5798f11e5c7cd0111cc3

Cheers

TOny

**Comment by dinkypumpkin** [comment] 2015-02-05 19:14
Duplicate of #464, #467

**Closed by dinkypumpkin** 2015-02-05 19:14 UTC
Labels: duplicate
