### ISSUE TITLE
itv list not being updated

### ISSUE THREAD

**Issue by cdebaixo** [GetiPlayerAutomator/get-iplayer-automator#548] opened 2016-04-08 08:48 UTC
Starting the App loads the bbc and itv programme lists which are then regularly updated. My update period is 4 hours.
Since 7.4.2016 the list does not appear to be up to date for itv programmes although it is for bbc.
I expected to see Episode 6 of the itv series Grantchester on my list but it was not either the day following the programme transmission nor the day following that. I have checked other itv programmes and the problem appears to be general and not just related to the series Grantchester.

I am using MAC OS X El Capitan

**Comment by dinkypumpkin** [comment] 2016-04-08 09:36
Save us both some time and check existing issues before posting.

Duplicate of #547

**Closed by dinkypumpkin** 2016-04-08 09:36 UTC
Labels: duplicate
