### ISSUE TITLE
Download failure when trying to download HD, Very High or High videos from BBC.

### ISSUE THREAD

**Issue by hubelot** [GetiPlayerAutomator/get-iplayer-automator#532] opened 2015-12-29 18:47 UTC
When trying to download BBC programmes in flashvhigh2, flashvhigh1 or flashhigh1 modes, the download fails.  It has, however, been working up till now in these modes.  Has the BBC changed anything in how they encode their videos?  If not, what can I try to get the HD mode working again?

Thank you.

=============================================================================

Extract from the log for the programme in question:

Downloading Show 1/1:

BBC Download (ID=99): Downloading Bad Education: Series 1 - School Trip
99:	Bad Education: Series 1 - School Trip, BBC Three, , default
INFO: 1 Matching Programmes
INFO: Checking existence of default version
INFO: flashhd1,flashvhigh2,flashvhigh1,flashhigh2,flashhigh1 modes will be tried for version default
INFO: Trying flashhd1 mode to record tv: Bad Education: Series 1 - 4. School Trip
INFO: File name prefix = Bad Education Series 1 - 4. School Trip ((flashhd))                 
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/gswann/Documents/gswann/Videos/iPlayer/Bad Education Series 1/Bad Education Series 1 - 4. School Trip ((flashhd)).partial.mp4.flv via RTMP
INFO: skipping flashhd1 mode
INFO: Trying flashvhigh2 mode to record tv: Bad Education: Series 1 - 4. School Trip
INFO: File name prefix = Bad Education Series 1 - 4. School Trip ((flashvhigh))                 
WARNING: HandShake: Type mismatch: client sent 3, server answered 21
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/gswann/Documents/gswann/Videos/iPlayer/Bad Education Series 1/Bad Education Series 1 - 4. School Trip ((flashvhigh)).partial.mp4.flv via RTMP
INFO: skipping flashvhigh2 mode
INFO: Trying flashvhigh1 mode to record tv: Bad Education: Series 1 - 4. School Trip
INFO: File name prefix = Bad Education Series 1 - 4. School Trip ((flashvhigh))                 
WARNING: HandShake: Type mismatch: client sent 3, server answered 21
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/gswann/Documents/gswann/Videos/iPlayer/Bad Education Series 1/Bad Education Series 1 - 4. School Trip ((flashvhigh)).partial.mp4.flv via RTMP
INFO: skipping flashvhigh1 mode
INFO: Trying flashhigh2 mode to record tv: Bad Education: Series 1 - 4. School Trip
INFO: File name prefix = Bad Education Series 1 - 4. School Trip ((flashhigh))                 
WARNING: HandShake: Type mismatch: client sent 3, server answered 21
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/gswann/Documents/gswann/Videos/iPlayer/Bad Education Series 1/Bad Education Series 1 - 4. School Trip ((flashhigh)).partial.mp4.flv via RTMP
INFO: skipping flashhigh2 mode
INFO: Trying flashhigh1 mode to record tv: Bad Education: Series 1 - 4. School Trip
INFO: File name prefix = Bad Education Series 1 - 4. School Trip ((flashhigh))                 
WARNING: HandShake: Type mismatch: client sent 3, server answered 21
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Command exit code 3 (raw code = 768)
WARNING: Failed to stream file /Users/gswann/Documents/gswann/Videos/iPlayer/Bad Education Series 1/Bad Education Series 1 - 4. School Trip ((flashhigh)).partial.mp4.flv via RTMP
INFO: skipping flashhigh1 mode
ERROR: Failed to record 'Bad Education: Series 1 - 4. School Trip (b01mgyty)'
BBC Download (ID=99): Bad Education: Series 1 - School Trip Failed

AppController: Downloads Finished

**Comment by dinkypumpkin** [comment] 2015-12-29 22:45
Likely duplicate of #483. Unless you can demonstrate that you are in the UK, there is nothing about your problem related to GiA.

**Closed by dinkypumpkin** 2015-12-29 22:45 UTC
Labels: duplicate, non-uk

**Comment by hubelot** [comment] 2016-01-07 15:54
Problem has resolved itself.  It seems to have coincided with an attack on the BBC's website, as reported here:

http://www.bbc.com/news/technology-35213415

**Comment by dinkypumpkin** [comment] 2016-01-07 16:21
The DDoS attack hit the BBC, not their CDNs, which is where the problem lay in your report.  Also, your report came 36 hours before the DDoS attack. Your programme downloaded fine at the time of the report, but that isn't to say there wasn't a problem with the CDN when you attempted to download. It's just not likely to be related to the DDoS attack that came 2 days later.
