### ISSUE TITLE
Saving Silent Witness files with incorrect name format

### ISSUE THREAD

**Issue by bobsthecoder** [GetiPlayerAutomator/get-iplayer-automator#457] opened 2015-01-21 06:55 UTC
While recording the current series of Silent Witness (series 18) all episodes are being saved with the filename format "Silent Witness Series 18 - 1. Part 1 ((flashhd)).mp4" and "Silent Witness Series 18 - 1. Part 2 ((flashhd)).mp4" for the two weekly episodes. 
This means that future episodes are not downloaded as the file name already exists.
The workaround is to rename the files once they have been downloaded, although they have already been imported to iTunes at this point.
For instance:
INFO: Getting page http://ichef.bbci.co.uk/images/ic/640x360/p02gtsx6.jpg
INFO: Downloaded Thumbnail to '/Volumes/.../BBC/Silent Witness Series 18/Silent Witness Series 18 - 2. Part 2 ((flashhd)).jpg'
INFO: MP4 tagging MP4 file
INFO: Command: "/Applications/Get iPlayer Automator.app/Contents/Resources/AtomicParsley" "/Volumes/.../BBC/Silent Witness Series 18/Silent Witness Series 18 - 2. Part 2 ((flashhd)).mp4" "--freefree" "--overWrite" "--stik" "TV Show" "--advisory" "explicit" "--copyright" "2015 British Broadcasting Corporation, all rights reserved" "--title" "Part 2" "--artist" "BBC One" "--albumArtist" "BBC TV" "--album" "Silent Witness: Series 18" "--grouping" "Drama,Crime" "--composer" "BBC iPlayer" "--genre" "Drama" "--comment" "Nikki, Jack and Thomas focus in on Lizzie's movements on the night of Barge's murder." "--year" "2015-01-20T21:00:00Z" "--tracknum" "2" "--disk" "18" "--lyrics" "Daniel Garvey is found dead in his car. Social worker Louise fears that he may have been killed by his 16-year-old stepson Kevin, who has just come out of care.
 Started writing to temp file.
INFO: Command exit code 0 (raw code = 0)
BBC Download (ID=1431): Silent Witness: Series 18 - Protection: Part 2 Completed Successfully

Next week, new episode:

INFO: File name prefix = Silent Witness Series 18 - 2. Part 2 ((flashhd))                 
WARNING: File /Volumes/.../BBC/Silent Witness Series 18/Silent Witness Series 18 - 2. Part 2 ((flashhd)).mp4 already exists
INFO: skipping this programme
ERROR: Failed to record 'Silent Witness: Series 18 - 2. Part 2 (b050m1sz)'

There does not seem to be an episode field in the original so maybe broadcast date could be used? The "title" is set to "part 1" and "part 2" for all episodes so this can not be used.

**Comment by dinkypumpkin** [comment] 2015-01-21 09:25
Duplicate of https://github.com/get-iplayer/get_iplayer/issues/112

**Closed** 2015-02-05 20:24 UTC
Labels: enhancement, Priority-Low
