### ISSUE TITLE
Test page not loading

### ISSUE THREAD

**Issue by fmrcBC** [GetiPlayerAutomator/get-iplayer-automator#563] opened 2016-05-20 21:39 UTC
[GiA16520a.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/275460/GiA16520a.txt)

What steps will reproduce the problem?
Tried downloading through several proxies (all WiTopia), used Safari and Chrome (same results), ITV.com, <Use Current Webpage> button to get program  (usually trying Marcella, but also tried others), 
after ca 30 sec, message: Proxy failed to load test page. Downloads may fail. Do you wish to continue?

What is the expected output? What do you see instead?
Normally the download cycle would begin. 

What version of GiA are you using? On what version of OS X?
Version 1.8.7-pre.3 (1756), OS X 10.9.4 and 10.11.4 and 10.11.5

What programme are you attempting to download (full title, series and episode)?
Marcella 

If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).
Attached 

Please provide any additional information below.
I know this is a constantly recurring problem and that 10.11.5 has additional complications, so I have tried working on Macs with a lower System. 
If I have it right, there are really two separate issues? 
---Not being able to get a program page into the queue at all (solved by the pre, but not in 10.11.5)
--Not getting the test page to load.  (Everywhere?) The only advice I have been able to find on that was simply to 'try again later'. 
I appreciate the value of the work being done to keep this program ahead of the Beeb and ITV countermeasures.
Will a new prerelease perhaps be addressing this issue? I haven’t seen much about this inte Wiki.

**Comment by dinkypumpkin** [comment] 2016-05-21 01:18
Duplicate of #559

**Closed by dinkypumpkin** 2016-05-21 01:18 UTC
Labels: duplicate
