### ISSUE TITLE
All BBC content suddenly not found/downloadable by Automator

### ISSUE THREAD

**Issue by naq59** [GetiPlayerAutomator/get-iplayer-automator#546] opened 2016-04-05 07:29 UTC
Suddenly this morning the Automator can´t find or download any BBC content (TV and radio). Regardless whether using the search function, inserting by hand or using "Use current website". The warning always comes that it says it can´t locate the the programme on the iPlayer and if outside the UK I should use a proxy. However, I can watch all the BBC shows directly on iPlayer using Overplay (from outside UK). ITV downloads work. I´ve tried the usual reinstall, restart, clear cache, etc. I noticed the download button is now missing from the iPlayer page when selecting individual programmes, maybe there´s a connection.
Mac OSX 10.10.5, Safari 9.0.1

**Comment by trackside** [comment] 2016-04-05 07:47
I am having the same issue. Using a proxy vpn everything is working fine but can not download from iplayer no matter what way I try.

**Comment by nitramlatep** [comment] 2016-04-05 09:12
Appears to be broken at the moment.  If you go to the closed issues 538 thread you will see that dinkypumpkin spotted this issue yesterday, but it appeared to be back to normal about an hour after that.  Since then it clearly has gone again.  BBC for sure changing things.  Hopefully it will come back by itself or if the changes the BBC have done are permanent then pray for a workaround.

**Comment by dinkypumpkin** [comment] 2016-04-05 09:22
Duplicate of #538

**Closed by dinkypumpkin** 2016-04-05 09:22 UTC

**Comment by naq59** [comment] 2016-04-05 09:55
Sorry, I looked but didn´t find the issue reported yesterday in #358. I just hope this does´t become a permanent issue with BBC
