### ISSUE TITLE
Cannot Download anything from BBC. ITV working fine.

### ISSUE THREAD

**Issue by 42south** [GetiPlayerAutomator/get-iplayer-automator#581] opened 2016-07-16 06:53 UTC
OSX 10.10.5
GIP Version 1.8.7-pre.4 (1763)
SmartDNS with Overplay.net

All downloads from BBC fail at initialisation. Everything else appears to be OK. Cache updates, can find and select programs, can get PID from "Use Current Webpage", But all downloads fail at initialisation. 

The example is a film: "A Hijacking". Log attached. This is typical of all download failures.

ITV downloads work perfectly.

Regards

Rex

[get iplayer automator log.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/367149/get.iplayer.automator.log.txt)

**Comment by dinkypumpkin** [comment] 2016-07-16 07:37
Save everyone some time and expend the minimal effort required to search existing tickets before posting. Duplicate of #580

**Closed by dinkypumpkin** 2016-07-16 07:37 UTC
Labels: duplicate
