### ISSUE TITLE
ITV not capturing PID links

### ISSUE THREAD

**Issue by 4x700** [GetiPlayerAutomator/get-iplayer-automator#527] opened 2015-11-21 21:21 UTC
Hi,

I have just had an issue with Get_iplayer not capturing links from the re-designed ITV website as they have changed the URL. I'm not sure if the ITV website is still using the same type of embedded flash player code as the interface has changed a bit as well to suit their new design.

Regards
Kevin

**Comment by dinkypumpkin** [comment] 2015-11-21 21:54
Duplicate of #525

**Closed by dinkypumpkin** 2015-11-21 21:54 UTC
Labels: duplicate
