### ISSUE TITLE
All BBC iPlayer downloads failing

### ISSUE THREAD

**Issue by lct1000** [GetiPlayerAutomator/get-iplayer-automator#521] opened 2015-11-02 23:29 UTC
Hello there,

I've been using Get iPlayer Automator for about a year and a half now. It has been working wonderfully until September this year. Now, everytime I attempt to download a BBC show (ITV works fine) I am told that the download failed. It says:
Problem Unknown
please submit a bug report from the application menu.

I have adjusted settings and constantly re-tried but nothing seems to work. Is anyone else having this issue? Am I doing something wrong?

Thanks :)

**Comment by dinkypumpkin** [comment] 2015-11-03 00:49
LIkely duplicate of #483. Unless you can demonstrate that you are in the UK, there is nothing about your problem related to GiA.

**Closed by dinkypumpkin** 2015-11-03 00:49 UTC
