### ISSUE TITLE
Not downloading HD version from BBC

### ISSUE THREAD

**Issue by Grimfool** [GetiPlayerAutomator/get-iplayer-automator#471] opened 2015-02-13 18:31 UTC
What steps will reproduce the problem?
Download any program
What is the expected output? What do you see instead?
would normally get the HD version as the default
What version of GiA are you using? On what version of OS X?
1.8.4 OSX 10.10.2
What programme are you attempting to download (full title, series and episode)?
Wolf Hall plus others
If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).

Please provide any additional information below.
Up until last week the default version of the program downloaded was the HD version. Then it started to download the high version instead. I can get the v.high version by deleting the low, standard & high formats from the BBC preferences but still cannot get the HD version

**Comment by dinkypumpkin** [comment] 2015-02-13 18:54
The instructions tell you to provide a verbose log for a reason. With no log provided, I can only assume this is a duplicate of #467.

**Closed by dinkypumpkin** 2015-02-13 18:54 UTC
