### ISSUE TITLE
Failed: No specific modes

### ISSUE THREAD

**Issue by ipodista** [GetiPlayerAutomator/get-iplayer-automator#595] opened 2016-09-04 18:17 UTC
Using V 1.8.6 on Mac OS X 10.11.6

When trying to download iPlayer programmes which are Olympic Events not broadcast but only made available over iPlayer, I am unable to locate the show via the search tool but instead have to go to the web page where I then use 'use current webpage' to load the PID and run I eventually get a Failed Download Solution - None of the download formats you specified were available for this show. I have got every format set in the pref tab.

Get iPlayer Automator 1.8.6 Initialized.

Updating Program Index Feeds from Server...
AppController: Index was Up-To-Date.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=p042zqlz): Downloading Olympic Cycling - Mountain Bike: 2016: Women's Cross-country
INFO: encodinglocale = UTF-8
INFO: encodinglocalefs = UTF-8
INFO: encodingconsoleout = UTF-8
INFO: encodingconsolein = UTF-8
INFO: ${^UNICODE} = 39
INFO: User prefs dir: /Users/adrianwalls_MP/Library/Application Support/Get iPlayer Automator
INFO: System options dir: /etc/get_iplayer/options
	versionlist = default
INFO: Search args: ''
INFO: Will try prog types: tv
INFO: Loaded history for first check.
INFO: Loading recordings history
INFO: Programme not in history
INFO: Got 2270 file cache entries for tv
INFO: Getting page http://www.bbc.co.uk/programmes/p042zqlz.rdf
INFO: Episode-only pid detected
INFO: Trying pid: p042zqlz using type: tv
INFO: Trying to stream pid using type tv
INFO: pid not found in tv cache
INFO: Cleaning pid Old: 'p042zqlz',  New: 'p042zqlz'
INFO: 1 Matching Programmes
INFO: Programme not in history
INFO: Programme metadata URL = http://www.bbc.co.uk/programmes/p042zqlz.xml
INFO: Getting page http://www.bbc.co.uk/programmes/p042zqlz.xml
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/p042zqm7/proto/rtmp?cb=93465
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/p042zqm7/proto/rtmp?cb=46381
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/p042zqm7/proto/http?cb=89360
INFO: Getting page http://vod-hls-uk-live.edgesuite.net/usp/auth/vod/piff_abr_l2v_hd/31927d-p042zqm7/vf_p042zqm7_9c4ee069-ea96-44ec-820f-5a359f3cd0cc.ism/mobile_wifi_main_sd_abr_v2_hls_master.m3u8?__gda__=1473034411_cc2c7a78cf4ea9f3d937eefb593844dc
INFO: Getting page http://vod-hls-uk-live.bbcfmt.vo.llnwd.net/usp/auth/vod/piff_abr_l2v_hd/31927d-p042zqm7/vf_p042zqm7_9c4ee069-ea96-44ec-820f-5a359f3cd0cc.ism/mobile_wifi_main_sd_abr_v2_hls_master.m3u8?s=1472991211&amp;e=1473034411&amp;h=50e6e40ebd8efa3a58d3fd8b04660a60
WARNING: No HLS playlist returned (http://vod-hls-uk-live.bbcfmt.vo.llnwd.net/usp/auth/vod/piff_abr_l2v_hd/31927d-p042zqm7/vf_p042zqm7_9c4ee069-ea96-44ec-820f-5a359f3cd0cc.ism/mobile_wifi_main_sd_abr_v2_hls_master.m3u8?s=1472991211&amp;e=1473034411&amp;h=50e6e40ebd8efa3a58d3fd8b04660a60)
INFO: Found mode hlshigh1: (gip_hls_iplayer_979) hls h264 704x396 979kbps stream (CDN: mf_akamai_uk_hls/1)
INFO: Found mode hlslow1: (gip_hls_iplayer_349) hls h264 384x216 349kbps stream (CDN: mf_akamai_uk_hls/1)
INFO: Found mode hlsstd1: (gip_hls_iplayer_565) hls h264 512x288 565kbps stream (CDN: mf_akamai_uk_hls/1)
INFO: Found mode hlsvhigh1: (gip_hls_iplayer_1802) hls h264 960x540 1802kbps stream (CDN: mf_akamai_uk_hls/1)
INFO: Getting page http://www.bbc.co.uk/programmes/p042zqm7.rdf
INFO: Using 'original' version (p042zqm7) as 'default'
INFO: Programme not in history
INFO: Will search for versions: default
INFO: Mode list: flashaachigh,flashaudio,flashhd2,flashhd1,flashvhigh2,flashvhigh1,flashhigh2,flashhigh1,flashstd2,flashstd1,flashlow2,flashlow1
INFO: Checking existence of default version
INFO: Version = default
INFO: No specified modes (flashaachigh,flashaudio,flashhd2,flashhd1,flashvhigh2,flashvhigh1,flashhigh2,flashhigh1,flashstd2,flashstd1,flashlow2,flashlow1) available for this programme with version 'default'
INFO: Try using --modes=hlshigh,hlslow,hlsstd,hlsvhigh
ERROR: Failed to record 'Olympic Cycling - Mountain Bike: 2016 - 1. Women's Cross-country (p042zqlz)'
REASON FOR FAILURE: None of the modes in your download format list are available for this show.
Try adding more modes.
BBC Download (ID=p042zqlz): Olympic Cycling - Mountain Bike: 2016: Women's Cross-country Failed

AppController: Downloads Finished
Updating Program Index Feeds from Server...
    Retrieving tv index feeds.
    Retrieving itv index feeds.
    Retrieving radio index feeds.
    Retrieving podcast index feeds.

**This issue tracker is not a discussion forum, so don't use it as such.  If you wish to discuss the BBC, iPlayer or anything else that is not related to an actual problem with the current release of GiA, post in an appropriate forum, not in this issue tracker.**

**STOP! DO NOT submit a ticket if you are unable to download a programme from outside the UK**. 

If you need an explanation, read [this](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/No-Support-for-GiA-Outside-the-UK). If you ignore this instruction, your ticket will be closed with no further action. You can fib about your location if you like, but you will only be wasting your time. If you are using GiA within the UK, continue with the instructions below.

Before creating a new ticket, search the current open and closed tickets to see if your issue has already been reported. Use the search box at the top of the page to do so. You can also use the links below to view open and closed tickets in list form. 

#### [Closed tickets](https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues?q=is%3Aissue+is%3Aclosed)

If you create a ticket for an issue that has already been reported, your ticket will be closed with no further action. If you are certain your issue has not yet been reported, continue with the instructions below.

Create a succinct title describing your issue in the `Title` field above, then provide the information requested below. If you do not provide the requested information, your ticket will be closed with no further action.

Delete the instructions above before submitting your ticket.

---

What steps will reproduce the problem? Be specific, and provide as much detail as possible.

What is the expected output? What do you see instead?

What version of GiA are you using? On what version of OS X?

Are you using a web proxy? DNS proxy? VPN? VPS?

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**

If you cannot download a programme, provide a verbose log of the attempt. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE programme. DO NOT post a massive log covering multiple multiple programme downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

Please provide any additional information below.

**Comment by dinkypumpkin** [comment] 2016-09-04 19:19
duplicate of #590

**Closed by dinkypumpkin** 2016-09-04 19:19 UTC
Labels: duplicate
