### ISSUE TITLE
Cannot download in HD

### ISSUE THREAD

**Issue by maheshkronecker** [GetiPlayerAutomator/get-iplayer-automator#468] opened 2015-02-09 23:12 UTC
What steps will reproduce the problem?
Attempt downloading one movie in HD format

What is the expected output? What do you see instead?
Fails with "unknown problem" message

What version of GiA are you using? On what version of OS X?
GiA Version 1.8.4 (1729) on Yosemite 10.10.2 (14C109)

What programme are you attempting to download (full title, series and episode)?
Father Brown: Series 2 - 7. The Three Tools of Death
(Note: the issue is the same with all HD programmes. Also, I tried to reproduce the error with only one file but GiA automatically updated the download list after failing and added a few more files)

If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).
https://gist.github.com/maheshkronecker/eb3fd4661a3c566adbb5

Please provide any additional information below.

**Comment by dinkypumpkin** [comment] 2015-02-18 15:53
Duplicate of #467

**Closed by dinkypumpkin** 2015-02-18 15:53 UTC
Labels: duplicate, non-uk
