### ISSUE TITLE
Sits at Initializing: 0.0%

### ISSUE THREAD

**Issue by timdafweak** [GetiPlayerAutomator/get-iplayer-automator#485] opened 2015-06-05 04:33 UTC
Not quite sure when this started. I am trying to download a program off BBC One Cambridgeshire, and the progress bar refuses to move. It stays stuck at Initializing: 0.0%

BBC Download (ID=775): Downloading Bargain Hunt: Series 36 - Edinburgh 4
INFO: Using Proxy xxx (where xxx is the provided Proxy).
775:	Bargain Hunt: Series 36 - Edinburgh 4, BBC One Cambridgeshire, , default
INFO: 1 Matching Programmes

I tried changing proxies too, same result.

**Comment by dinkypumpkin** [comment] 2015-06-05 08:16
Most likely duplicate of #483

**Closed by dinkypumpkin** 2015-06-05 08:16 UTC
