### ISSUE TITLE
Only getting flash low BBC programmes

### ISSUE THREAD

**Issue by gacres2** [GetiPlayerAutomator/get-iplayer-automator#562] opened 2016-05-20 17:53 UTC
For about a week now I've only been able to get the low quality (small) files for BBC programmes. It tries all the higher res versions but they all fail. I've attached a snippet of log that seems to include one of the many failing moments. What is striking is that it each attempt has to wait to time out and so it takes a very long time to get started and then because the file is small it downloads very quickly.

I'm running the 1.8.7 pre3 build. Let me know if you need more log or want me to try something else. I get the same behavior across two different machines on completely different ISPs.

[log.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/275161/log.txt)

**Comment by dinkypumpkin** [comment] 2016-05-21 01:16
You have most likely been rumbled by the BBC. Duplicate of #483 unless ou can prove otherwise.

**Closed by dinkypumpkin** 2016-05-21 01:16 UTC
Labels: duplicate
