### ISSUE TITLE
Download Top Gear Series 22 - Episode 3 (HD) fails at 592.6Mb

### ISSUE THREAD

**Issue by approtech** [GetiPlayerAutomator/get-iplayer-automator#470] opened 2015-02-11 19:34 UTC
This issue appears similar to others recently closed, but I am in the UK not overseas.

I have attempted to download the most recent episode of Top Gear (Series 22 - Episode 3) about 6 times since it became available. It starts OK, and keeps going until the file reaches 592.6Mb as reported by Finder (always the same size). The file is then left as "Top Gear Series 22 - 3. Episode 3 ((flashhd)).partial.mp4" The file starts playing OK in VLC, which reports its duration as 1:02:28; it appears to play successfully up to about 33 minutes, then goes black and closes the VLC window.

No problems with any other HD programmes, including episodes 1 & 2 of Top Gear and this week's Holby City (I tried a show broadcast since the problematic Top Gear, of a similar length, hopefully to eliminate file-size or recent generic changes as possible causes).

Verbose log link:

https://gist.github.com/approtech/ac65702e4f37a7158df8

**Comment by dinkypumpkin** [comment] 2015-02-13 11:33
Thanks for the log. This a duplicate of #467.  Even though you're in the UK, the underlying problem is the same: the Level3 CDN is broken.  In your example, the partial output file was garbaged and thus get_iplayer didn't flip over to the Akamai CDN available to UK users.  There is nothing GiA can do about this. All you can do is delete the partial download and try again.  Alternatively, you can install get_iplayer itself, which provides a means to avoid the broken Level3 CDN.

**Closed by dinkypumpkin** 2015-02-13 11:33 UTC
Labels: duplicate
